[package]
name = "may_connectors"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1"
futures = "0.3"
may_secrets = { version = "0.1.0", path = "../may_secrets" }
rustls = { version = "0.23.40", features = ["ring"] }
rustls-native-certs = "0.8.4"
thiserror = "2.0"
tokio = { version = "1.0", features = ["sync", "rt", "net", "macros"] }
tokio-postgres = "0.7.17"
tokio-postgres-rustls = "0.14.0"
[lints]
workspace = true
