{{- if .Values.identityDb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-identity-db
  labels:
    app: {{ .Release.Name }}-identity-db
type: Opaque
data:
  POSTGRES_USER: {{ .Values.identityDb.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.identityDb.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.identityDb.database | b64enc | quote }}
{{- end }}
