{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: {{ .Release.Name }}-vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app: {{ .Release.Name }}-vault
{{- end }}
