[package]
name = "may_secrets"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { workspace = true }

[dev-dependencies]
serial_test = "3.1"

[lints]
workspace = true
